import { registerTemplates } from "../registry";
import type { PageTemplate } from "../types";

// ============================================================================
// GritCMS Page Templates — 117 templates across 19 categories
// ============================================================================

const templates: PageTemplate[] = [
  // ==========================================================================
  // 0. Creator Home — DEFAULT template (Ali Abdaal inspired)
  // ==========================================================================
  {
    id: "creator-home",
    category: "creator",
    name: "Creator Home",
    description:
      "The ultimate GritCMS creator homepage — showcases all modules. Personal greeting hero, service cards, live courses, YouTube videos, digital products, blog feed, community, booking, newsletter, and social links.",
    tags: ["creator", "default", "personal-brand", "home", "all-modules"],
    sections: [
      { sectionId: "header-003", props: { logo: "{{site_name}}", links: "Home, Courses, Products, Blog, Community, Book a Call, Contact" } },
      { sectionId: "hero-002", props: { heading: "Hey Friends 👋", subheading: "Welcome to my corner of the internet. I'm a creator, educator, and entrepreneur sharing ideas on productivity, creativity, and building a life you love.", primaryCta: "Subscribe to Newsletter", secondaryCta: "Explore Courses" } },
      { sectionId: "live-010", props: { heading: "Connect With Me", youtube: "https://youtube.com/@yourchannel", twitter: "https://twitter.com/yourhandle", instagram: "https://instagram.com/yourhandle", linkedin: "https://linkedin.com/in/yourprofile", tiktok: "https://tiktok.com/@yourhandle", github: "" } },
      { sectionId: "features-003", props: { heading: "How Can I Help You?", subheading: "I create content, courses, and products to help you level up.", feature1Title: "Grow Your Audience", feature1Desc: "Learn strategies to build and engage your audience across platforms.", feature2Title: "Be More Productive", feature2Desc: "Science-backed productivity tips and systems to get more done.", feature3Title: "Build Your Business", feature3Desc: "Step-by-step guides to monetize your skills and build online income." } },
      { sectionId: "live-008", props: { heading: "Featured Course", subheading: "My flagship course — the best place to start.", dataSource: "courses", limit: 1 } },
      { sectionId: "live-001", props: { heading: "Explore My Courses", subheading: "Self-paced programs to help you master new skills.", dataSource: "courses", limit: 6 } },
      { sectionId: "live-007", props: { heading: "Watch My Latest Videos", subheading: "New videos every week on YouTube.", videos: [{ url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", title: "Replace with your video URL" }] } },
      { sectionId: "about-001", props: { heading: "Hey, I'm {{site_name}}", description: "I'm a creator and educator passionate about sharing what I learn. This platform is where I share my courses, articles, videos, and resources to help you live a more productive and fulfilling life." } },
      { sectionId: "live-002", props: { heading: "Digital Products & Resources", subheading: "Templates, ebooks, and tools I've created for you.", dataSource: "products", limit: 4 } },
      { sectionId: "live-003", props: { heading: "From the Blog", subheading: "Deep dives, tutorials, and written guides.", dataSource: "posts", limit: 3 } },
      { sectionId: "live-005", props: { heading: "Join the Community", subheading: "Connect with like-minded creators and learners.", dataSource: "community", limit: 3 } },
      { sectionId: "live-006", props: { heading: "Book a Call", subheading: "Schedule a one-on-one session for personalized guidance.", dataSource: "booking" } },
      { sectionId: "live-009", props: { heading: "What People Are Saying", subheading: "Hear from students, clients, and community members." } },
      { sectionId: "live-004", props: { heading: "Join the Newsletter", subheading: "Get weekly insights on productivity, creativity, and building your dream life. Join 100,000+ subscribers.", buttonText: "Subscribe", dataSource: "newsletter" } },
      { sectionId: "footer-002", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },

  // ==========================================================================
  // 1a. Content Creator (3 templates)
  // ==========================================================================
  {
    id: "content-creator-01",
    category: "content-creator",
    name: "YouTuber Home",
    description:
      "YouTube-focused creator homepage with personal greeting hero, embedded video feed, blog articles, newsletter signup, and about section.",
    tags: ["youtube", "creator", "video", "personal-brand"],
    sections: [
      { sectionId: "header-002", props: { logo: "{{site_name}}", links: "Home, Videos, Blog, About, Contact" } },
      { sectionId: "hero-002", props: { heading: "Hey, Welcome to My Channel!", subheading: "I make videos about creativity, tech, and living a more intentional life. Subscribe and join the journey.", primaryCta: "Subscribe on YouTube", secondaryCta: "Latest Video" } },
      { sectionId: "live-007", props: { heading: "Latest Videos", subheading: "Catch up on my most recent uploads." } },
      { sectionId: "features-003", props: { heading: "How I Can Help You", subheading: "I create content to help you level up in these areas.", feature1Title: "Grow on YouTube", feature1Desc: "Strategies and tips for building your channel from zero.", feature2Title: "Creative Workflows", feature2Desc: "Tools and processes to create content faster and better.", feature3Title: "Monetize Your Passion", feature3Desc: "Turn your hobby into a sustainable online business." } },
      { sectionId: "live-003", props: { heading: "From the Blog", subheading: "Deep dives and written guides on the topics I cover in my videos." } },
      { sectionId: "live-004", props: { heading: "Join the Creator Newsletter", subheading: "Weekly tips on YouTube growth, creativity, and building an audience. Join 50,000+ creators." } },
      { sectionId: "about-001", props: { heading: "About Me", description: "I'm a full-time creator sharing everything I learn about building an audience, making great content, and turning your passion into a career." } },
      { sectionId: "footer-002", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },
  {
    id: "content-creator-02",
    category: "content-creator",
    name: "Podcaster Home",
    description:
      "Podcast-focused creator homepage with episode highlights, topic features, latest episode video embed, testimonials, and newsletter signup.",
    tags: ["podcast", "audio", "creator", "episodes"],
    sections: [
      { sectionId: "header-003", props: { logo: "{{site_name}}", links: "Home, Episodes, Topics, About, Subscribe" } },
      { sectionId: "hero-004", props: { heading: "Conversations That Matter", subheading: "A weekly podcast exploring ideas at the intersection of technology, culture, and human potential. Listen on all platforms.", primaryCta: "Listen Now", secondaryCta: "Browse Episodes" } },
      { sectionId: "features-005", props: { heading: "What We Cover", subheading: "Deep conversations on the topics that shape our world.", feature1Title: "Technology & Innovation", feature1Desc: "How emerging tech is changing the way we live and work.", feature2Title: "Mindset & Growth", feature2Desc: "Mental models and habits for personal and professional growth.", feature3Title: "Entrepreneurship", feature3Desc: "Stories and strategies from founders building the future." } },
      { sectionId: "video-002", props: { heading: "Latest Episode", subheading: "Watch or listen to the most recent conversation." } },
      { sectionId: "live-003", props: { heading: "Show Notes & Articles", subheading: "Written companion pieces and expanded thoughts from recent episodes." } },
      { sectionId: "testimonials-002", props: { heading: "What Listeners Say", subheading: "Reviews from our amazing community of listeners." } },
      { sectionId: "live-004", props: { heading: "Get Episode Updates", subheading: "Never miss an episode. Get show notes and bonus content delivered to your inbox." } },
      { sectionId: "footer-003", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },
  {
    id: "content-creator-03",
    category: "content-creator",
    name: "Multi-Platform Creator",
    description:
      "Multi-platform creator homepage with social links, video feed, blog posts, product showcase, and newsletter for creators active across YouTube, social media, and blogs.",
    tags: ["multi-platform", "creator", "social", "content"],
    sections: [
      { sectionId: "header-002", props: { logo: "{{site_name}}", links: "Home, Content, Products, Blog, About" } },
      { sectionId: "hero-001", props: { heading: "Welcome to My World", subheading: "Creator, educator, and entrepreneur. I share ideas across YouTube, Instagram, TikTok, and my blog to help you build a life and career you love.", primaryCta: "Explore My Content", secondaryCta: "Shop Resources" } },
      { sectionId: "live-010", props: { heading: "Follow Me Everywhere", subheading: "Connect with me across all platforms." } },
      { sectionId: "features-003", props: { heading: "What I Create", subheading: "Content and resources across multiple formats and platforms.", feature1Title: "Video Content", feature1Desc: "Weekly YouTube videos and short-form content on social media.", feature2Title: "Written Guides", feature2Desc: "In-depth blog posts and newsletters on creativity and business.", feature3Title: "Digital Products", feature3Desc: "Templates, courses, and tools to accelerate your growth." } },
      { sectionId: "live-007", props: { heading: "Latest Videos", subheading: "My most recent video content from across platforms." } },
      { sectionId: "live-003", props: { heading: "From the Blog", subheading: "Long-form articles and written guides." } },
      { sectionId: "live-002", props: { heading: "My Products & Resources", subheading: "Tools, templates, and courses I've created for you." } },
      { sectionId: "live-004", props: { heading: "The Weekly Dispatch", subheading: "One email per week with my best content, curated links, and behind-the-scenes updates." } },
      { sectionId: "footer-001", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },

  // ==========================================================================
  // 1b. Coach & Consultant (3 templates)
  // ==========================================================================
  {
    id: "coach-01",
    category: "coach",
    name: "Business Coach",
    description:
      "Business coaching homepage with coaching areas, client testimonials, session booking, course offerings, impact stats, and strong call to action.",
    tags: ["business-coach", "coaching", "consulting", "mentorship"],
    sections: [
      { sectionId: "header-001", props: { logo: "{{site_name}}", links: "Home, Programs, Testimonials, Book a Call, Courses" } },
      { sectionId: "hero-003", props: { heading: "Scale Your Business With Expert Guidance", subheading: "I help entrepreneurs and business owners build systems, increase revenue, and create businesses that run without them.", primaryCta: "Book a Free Discovery Call", secondaryCta: "View Programs" } },
      { sectionId: "features-002", props: { heading: "How I Help You Grow", subheading: "Focused coaching in the areas that matter most for your business.", feature1Title: "Revenue Growth", feature1Desc: "Proven strategies to increase sales and build predictable income.", feature2Title: "Team & Operations", feature2Desc: "Build the right team and systems so your business runs without you.", feature3Title: "Strategic Planning", feature3Desc: "Clear roadmaps and accountability to hit your biggest goals." } },
      { sectionId: "testimonials-003", props: { heading: "Client Success Stories", subheading: "Hear from business owners who transformed their results." } },
      { sectionId: "live-006", props: { heading: "Book a Coaching Session", subheading: "Schedule a one-on-one session and start making progress today." } },
      { sectionId: "live-001", props: { heading: "Self-Paced Programs", subheading: "Learn at your own pace with my comprehensive online courses." } },
      { sectionId: "stats-002", props: { heading: "The Results Speak", stat1: "500+", stat1Label: "Clients Coached", stat2: "$50M+", stat2Label: "Revenue Generated", stat3: "4.9/5", stat3Label: "Average Rating" } },
      { sectionId: "cta-003", props: { heading: "Ready to Transform Your Business?", subheading: "Book your free discovery call and let's create your growth plan.", primaryCta: "Book a Call" } },
      { sectionId: "footer-001", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },
  {
    id: "coach-02",
    category: "coach",
    name: "Life Coach",
    description:
      "Life and wellness coaching homepage with personal about section, coaching areas, testimonials, session booking, pricing plans, and newsletter.",
    tags: ["life-coach", "wellness", "mindset", "personal-development"],
    sections: [
      { sectionId: "header-003", props: { logo: "{{site_name}}", links: "Home, About, Services, Testimonials, Book a Session" } },
      { sectionId: "hero-005", props: { heading: "Transform Your Life With Expert Guidance", subheading: "I help individuals break through limitations, find clarity, and design a life aligned with their deepest values and aspirations.", primaryCta: "Start Your Journey", secondaryCta: "Learn More" } },
      { sectionId: "about-002", props: { heading: "My Story", description: "After years of personal transformation and hundreds of clients helped, I've developed a proven framework for lasting change. I believe everyone deserves a life of purpose, joy, and fulfillment." } },
      { sectionId: "features-004", props: { heading: "Areas of Coaching", subheading: "Personalized support across the dimensions of your life.", feature1Title: "Mindset & Confidence", feature1Desc: "Overcome limiting beliefs and build unshakeable self-confidence.", feature2Title: "Career & Purpose", feature2Desc: "Find meaningful work and align your career with your values.", feature3Title: "Relationships & Wellbeing", feature3Desc: "Build deeper connections and cultivate holistic wellness." } },
      { sectionId: "testimonials-005", props: { heading: "Transformation Stories", subheading: "Real people, real breakthroughs." } },
      { sectionId: "live-006", props: { heading: "Book Your Session", subheading: "Take the first step toward the life you deserve." } },
      { sectionId: "pricing-003", props: { heading: "Coaching Packages", subheading: "Choose the level of support that's right for you." } },
      { sectionId: "live-004", props: { heading: "Weekly Inspiration", subheading: "Mindset tips, reflections, and actionable advice delivered to your inbox every week." } },
      { sectionId: "footer-003", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },
  {
    id: "coach-03",
    category: "coach",
    name: "Fitness Coach",
    description:
      "Fitness and health coaching homepage with transformation gallery, online programs, pricing plans, client testimonials, session booking, and impact stats.",
    tags: ["fitness-coach", "health", "training", "transformation"],
    sections: [
      { sectionId: "header-002", props: { logo: "{{site_name}}", links: "Home, Programs, Transformations, Pricing, Book a Call" } },
      { sectionId: "hero-002", props: { heading: "Your Strongest Self Starts Here", subheading: "Personalized training programs, nutrition coaching, and accountability to help you achieve the body and health you've always wanted.", primaryCta: "Start Your Transformation", secondaryCta: "View Programs" } },
      { sectionId: "gallery-002", props: { heading: "Client Transformations", subheading: "Real results from real people following my programs." } },
      { sectionId: "live-001", props: { heading: "Training Programs", subheading: "Structured programs for every fitness level and goal." } },
      { sectionId: "pricing-002", props: { heading: "Coaching Plans", subheading: "Choose the plan that fits your goals and budget." } },
      { sectionId: "testimonials-002", props: { heading: "What My Clients Say", subheading: "Hear from people who've transformed their bodies and lives." } },
      { sectionId: "live-006", props: { heading: "Book a Free Consultation", subheading: "Let's discuss your goals and find the right program for you." } },
      { sectionId: "stats-001", props: { heading: "By the Numbers", stat1: "1,000+", stat1Label: "Clients Trained", stat2: "15+", stat2Label: "Years Experience", stat3: "98%", stat3Label: "Goal Achievement Rate" } },
      { sectionId: "footer-002", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },

  // ==========================================================================
  // 1c. Course Creator (3 templates)
  // ==========================================================================
  {
    id: "course-creator-01",
    category: "course-creator",
    name: "Course Platform",
    description:
      "Full-featured course creator homepage with featured course spotlight, course catalog, student testimonials, impact stats, newsletter, and FAQ.",
    tags: ["courses", "online-education", "learning", "creator"],
    sections: [
      { sectionId: "header-001", props: { logo: "{{site_name}}", links: "Home, Courses, About, Testimonials, FAQ" } },
      { sectionId: "hero-001", props: { heading: "Learn Skills That Change Your Life", subheading: "Practical, project-based courses designed to take you from beginner to expert. Join thousands of students already learning.", primaryCta: "Browse Courses", secondaryCta: "Free Preview" } },
      { sectionId: "live-008", props: { heading: "Featured Course", subheading: "My most popular course — start here." } },
      { sectionId: "live-001", props: { heading: "All Courses", subheading: "Explore the full library of courses and start learning today." } },
      { sectionId: "testimonials-001", props: { heading: "Student Success Stories", subheading: "See what students are saying about their learning experience." } },
      { sectionId: "stats-003", props: { heading: "Our Impact", stat1: "25,000+", stat1Label: "Students Enrolled", stat2: "50+", stat2Label: "Hours of Content", stat3: "4.8/5", stat3Label: "Average Rating" } },
      { sectionId: "live-004", props: { heading: "Get Free Lessons", subheading: "Subscribe for free tutorials, course updates, and exclusive learning resources." } },
      { sectionId: "faq-002", props: { heading: "Frequently Asked Questions", subheading: "Everything you need to know before enrolling." } },
      { sectionId: "footer-001", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },
  {
    id: "course-creator-02",
    category: "course-creator",
    name: "Workshop Host",
    description:
      "Workshop and masterclass creator homepage with intro video, workshop catalog, pricing tiers, testimonials, session booking, and enrollment CTA.",
    tags: ["workshops", "masterclass", "live-learning", "creator"],
    sections: [
      { sectionId: "header-003", props: { logo: "{{site_name}}", links: "Home, Workshops, Pricing, Testimonials, Book a Spot" } },
      { sectionId: "hero-003", props: { heading: "Hands-On Workshops That Deliver Results", subheading: "Small-group, interactive workshops and masterclasses designed to give you actionable skills you can apply immediately.", primaryCta: "View Upcoming Workshops", secondaryCta: "Watch Intro" } },
      { sectionId: "video-001", props: { heading: "See What a Workshop Looks Like", subheading: "Get a behind-the-scenes look at the learning experience." } },
      { sectionId: "live-001", props: { heading: "Upcoming Workshops", subheading: "Browse available workshops and masterclasses." } },
      { sectionId: "pricing-004", props: { heading: "Pricing & Packages", subheading: "Single workshops, bundles, and all-access passes." } },
      { sectionId: "testimonials-004", props: { heading: "What Attendees Say", subheading: "Feedback from past workshop participants." } },
      { sectionId: "live-006", props: { heading: "Reserve Your Spot", subheading: "Workshops are limited in size to ensure quality. Book early." } },
      { sectionId: "cta-002", props: { heading: "Ready to Level Up?", subheading: "Join the next workshop and gain skills you'll use forever.", primaryCta: "Browse Workshops" } },
      { sectionId: "footer-003", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },
  {
    id: "course-creator-03",
    category: "course-creator",
    name: "Academy",
    description:
      "Full online academy homepage with 'as seen on' logos, complete course catalog, featured course spotlight, impact stats, testimonials, pricing, and newsletter.",
    tags: ["academy", "education", "online-school", "creator"],
    sections: [
      { sectionId: "header-001", props: { logo: "{{site_name}}", links: "Home, Courses, About, Pricing, Testimonials" } },
      { sectionId: "hero-005", props: { heading: "The Academy for Modern Professionals", subheading: "A world-class online academy offering comprehensive courses taught by industry experts. Start learning today and transform your career.", primaryCta: "Explore the Academy", secondaryCta: "Free Trial" } },
      { sectionId: "logos-002", props: { heading: "As Seen On", subheading: "Featured in leading publications and platforms." } },
      { sectionId: "live-001", props: { heading: "Course Catalog", subheading: "Browse our complete library of professional courses." } },
      { sectionId: "live-008", props: { heading: "Course Spotlight", subheading: "Our most popular course this month." } },
      { sectionId: "stats-002", props: { heading: "Academy Impact", stat1: "100,000+", stat1Label: "Students Worldwide", stat2: "200+", stat2Label: "Courses Available", stat3: "95%", stat3Label: "Completion Rate" } },
      { sectionId: "testimonials-003", props: { heading: "Student Testimonials", subheading: "Hear from students who've advanced their careers with us." } },
      { sectionId: "pricing-003", props: { heading: "Membership Plans", subheading: "Get unlimited access to all courses with a membership." } },
      { sectionId: "live-004", props: { heading: "Stay in the Loop", subheading: "Get notified about new courses, free workshops, and exclusive offers." } },
      { sectionId: "footer-001", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },

  // ==========================================================================
  // 1d. Author & Writer (2 templates)
  // ==========================================================================
  {
    id: "author-01",
    category: "author",
    name: "Author Home",
    description:
      "Book author homepage with book showcase, author bio, articles/blog feed, reader testimonials, and newsletter signup.",
    tags: ["author", "books", "writing", "publishing"],
    sections: [
      { sectionId: "header-002", props: { logo: "{{site_name}}", links: "Home, Books, Articles, About, Contact" } },
      { sectionId: "hero-004", props: { heading: "Stories That Stay With You", subheading: "Bestselling author of fiction and non-fiction books exploring the human experience. Discover my latest work and join the reading community.", primaryCta: "Browse My Books", secondaryCta: "Read Latest Article" } },
      { sectionId: "ecommerce-002", props: { heading: "My Books", subheading: "Explore my published works — available in hardcover, paperback, and digital." } },
      { sectionId: "about-003", props: { heading: "About the Author", description: "I've been writing for over a decade, with works published in multiple languages. My writing explores themes of identity, purpose, and the stories we tell ourselves. When I'm not writing, you'll find me reading, traveling, or speaking at literary events." } },
      { sectionId: "live-003", props: { heading: "Articles & Essays", subheading: "Thoughts on writing, creativity, and life." } },
      { sectionId: "testimonials-006", props: { heading: "Reader Reviews", subheading: "What readers are saying about my books." } },
      { sectionId: "live-004", props: { heading: "The Author's Letter", subheading: "Behind-the-scenes updates, reading recommendations, and early access to new releases." } },
      { sectionId: "footer-002", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },
  {
    id: "author-02",
    category: "author",
    name: "Thought Leader",
    description:
      "Thought leadership platform with blog feed, expertise areas, impact stats, about section, courses, and newsletter signup.",
    tags: ["thought-leader", "expert", "ideas", "influence"],
    sections: [
      { sectionId: "header-001", props: { logo: "{{site_name}}", links: "Home, Ideas, About, Courses, Newsletter" } },
      { sectionId: "hero-001", props: { heading: "Ideas That Shape the Future", subheading: "I write, speak, and teach about the forces reshaping business, technology, and society. Explore my latest thinking and join the conversation.", primaryCta: "Read Latest", secondaryCta: "Browse Courses" } },
      { sectionId: "live-003", props: { heading: "Latest Thinking", subheading: "Essays, analyses, and frameworks on the topics that matter." } },
      { sectionId: "features-001", props: { heading: "Areas of Expertise", subheading: "Deep knowledge across the domains that drive modern business.", feature1Title: "Future of Work", feature1Desc: "How technology and culture are transforming the workplace.", feature2Title: "Digital Transformation", feature2Desc: "Strategies for organizations navigating technological change.", feature3Title: "Leadership & Strategy", feature3Desc: "Principles for leading in an uncertain and complex world." } },
      { sectionId: "stats-001", props: { heading: "Reach & Impact", stat1: "5M+", stat1Label: "Annual Readers", stat2: "200+", stat2Label: "Keynote Talks", stat3: "3", stat3Label: "Bestselling Books" } },
      { sectionId: "about-001", props: { heading: "About Me", description: "I'm a researcher, author, and keynote speaker helping leaders and organizations navigate the future. My work has been featured in major publications and I've advised Fortune 500 companies on strategy and innovation." } },
      { sectionId: "live-001", props: { heading: "Courses & Programs", subheading: "Go deeper with structured learning experiences." } },
      { sectionId: "live-004", props: { heading: "The Weekly Brief", subheading: "One essential idea per week, delivered straight to your inbox. Join 100,000+ subscribers." } },
      { sectionId: "footer-001", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },

  // ==========================================================================
  // 1e. Musician & Artist (2 templates)
  // ==========================================================================
  {
    id: "musician-01",
    category: "musician",
    name: "Musician Home",
    description:
      "Solo musician homepage with music videos, photo gallery, merchandise store, artist bio, social links, and newsletter.",
    tags: ["musician", "solo-artist", "music", "performer"],
    sections: [
      { sectionId: "header-004", props: { logo: "{{site_name}}", links: "Home, Music, Photos, Merch, About" } },
      { sectionId: "hero-006", props: { heading: "New Album Out Now", subheading: "Experience the latest album — a journey through sound, emotion, and storytelling. Stream everywhere or get the limited vinyl edition.", primaryCta: "Listen Now", secondaryCta: "Get the Vinyl" } },
      { sectionId: "live-007", props: { heading: "Music Videos", subheading: "Watch the latest official music videos and live performances." } },
      { sectionId: "gallery-003", props: { heading: "Photos", subheading: "Behind the scenes, live shows, and studio sessions." } },
      { sectionId: "live-002", props: { heading: "Merch Store", subheading: "Official merchandise — apparel, vinyl, posters, and limited editions." } },
      { sectionId: "about-004", props: { heading: "About the Artist", description: "A genre-bending musician blending elements of indie, electronic, and folk. With multiple albums and world tours, the music continues to evolve and push creative boundaries." } },
      { sectionId: "live-010", props: { heading: "Connect", subheading: "Follow on all platforms for tour dates, new releases, and behind-the-scenes content." } },
      { sectionId: "footer-004", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },
  {
    id: "musician-02",
    category: "musician",
    name: "Band Website",
    description:
      "Band or group homepage with music videos, photo gallery, merchandise, community, band bio, newsletter, and social links.",
    tags: ["band", "group", "music", "rock"],
    sections: [
      { sectionId: "header-005", props: { logo: "{{site_name}}", links: "Home, Music, Gallery, Merch, Community, About" } },
      { sectionId: "hero-008", props: { heading: "We Are {{site_name}}", subheading: "Loud, raw, and unapologetic. Our new record drops this spring — pre-order now and join the movement.", primaryCta: "Pre-Order Now", secondaryCta: "Tour Dates" } },
      { sectionId: "live-007", props: { heading: "Videos", subheading: "Official videos, live footage, and behind-the-scenes content." } },
      { sectionId: "gallery-005", props: { heading: "Gallery", subheading: "Tour photos, studio sessions, and fan moments." } },
      { sectionId: "live-002", props: { heading: "Merch", subheading: "Rep the band — shirts, hoodies, vinyl, and exclusive gear." } },
      { sectionId: "live-005", props: { heading: "Fan Community", subheading: "Join the conversation with fellow fans." } },
      { sectionId: "about-005", props: { heading: "About the Band", description: "Formed in a garage, forged on the road. We've been making music together for over a decade, touring the world, and building a community of fans who believe in the power of live music." } },
      { sectionId: "live-004", props: { heading: "Mailing List", subheading: "Be first to know about new music, tour dates, and exclusive fan-only content." } },
      { sectionId: "footer-005", props: { logo: "{{site_name}}", copyright: "© 2026 {{site_name}}. All rights reserved." } },
    ],
  },

  // ==========================================================================
  // 1. SaaS / Tech (12 templates)
  // ==========================================================================
  {
    id: "saas-landing-01",
    category: "saas",
    name: "SaaS Product Launch",
    description:
      "Modern SaaS landing page with a bold hero, trusted-by logos, feature grid, pricing table, testimonials, and a strong call to action.",
    tags: ["saas", "modern", "professional", "launch"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-001", props: { heading: "Launch Your SaaS Product" } },
      { sectionId: "logos-001" },
      { sectionId: "features-001" },
      { sectionId: "pricing-002" },
      { sectionId: "testimonials-002" },
      { sectionId: "cta-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "saas-landing-02",
    category: "saas",
    name: "Startup MVP",
    description:
      "Lean startup landing page designed to validate ideas fast with a clear value proposition, early-adopter signup, and social proof.",
    tags: ["startup", "mvp", "lean", "modern"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-003", props: { heading: "Build. Ship. Grow." } },
      { sectionId: "features-003" },
      { sectionId: "stats-001" },
      { sectionId: "testimonials-001" },
      { sectionId: "newsletter-001" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "saas-landing-03",
    category: "saas",
    name: "AI Tool Platform",
    description:
      "Showcase an AI-powered tool with a demo video, feature highlights, integration logos, and a free-trial CTA.",
    tags: ["ai", "technology", "platform", "futuristic"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-005", props: { heading: "AI That Works For You" } },
      { sectionId: "video-001" },
      { sectionId: "features-005" },
      { sectionId: "logos-002" },
      { sectionId: "pricing-003" },
      { sectionId: "faq-001" },
      { sectionId: "cta-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "saas-landing-04",
    category: "saas",
    name: "Developer Platform",
    description:
      "Technical landing page aimed at developers with code examples, API documentation links, and integration showcases.",
    tags: ["developer", "api", "technical", "platform"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-007", props: { heading: "The API Developers Love" } },
      { sectionId: "features-007" },
      { sectionId: "stats-003" },
      { sectionId: "logos-003" },
      { sectionId: "testimonials-003" },
      { sectionId: "pricing-004" },
      { sectionId: "cta-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "saas-landing-05",
    category: "saas",
    name: "Analytics Dashboard",
    description:
      "Data-driven landing page for analytics platforms featuring visual stats, feature deep-dives, and enterprise-ready pricing.",
    tags: ["analytics", "data", "dashboard", "enterprise"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-009", props: { heading: "Actionable Insights, Instantly" } },
      { sectionId: "stats-005" },
      { sectionId: "features-009" },
      { sectionId: "video-002" },
      { sectionId: "pricing-005" },
      { sectionId: "testimonials-005" },
      { sectionId: "cta-005" },
      { sectionId: "footer-005" },
    ],
  },
  {
    id: "saas-landing-06",
    category: "saas",
    name: "Mobile App Showcase",
    description:
      "App landing page with device mockups, app store badges, feature carousel, and user reviews.",
    tags: ["mobile", "app", "ios", "android"],
    sections: [
      { sectionId: "header-006" },
      { sectionId: "hero-011", props: { heading: "Your Life, One App Away" } },
      { sectionId: "features-011" },
      { sectionId: "gallery-001" },
      { sectionId: "testimonials-006" },
      { sectionId: "stats-006" },
      { sectionId: "cta-006" },
      { sectionId: "footer-006" },
    ],
  },
  {
    id: "saas-landing-07",
    category: "saas",
    name: "API Product",
    description:
      "Clean API product page with endpoint previews, SDKs, integration partners, and developer-friendly pricing.",
    tags: ["api", "developer", "integration", "technical"],
    sections: [
      { sectionId: "header-007" },
      { sectionId: "hero-013", props: { heading: "One API, Endless Possibilities" } },
      { sectionId: "features-013" },
      { sectionId: "logos-004" },
      { sectionId: "pricing-007" },
      { sectionId: "faq-003" },
      { sectionId: "cta-007" },
      { sectionId: "footer-007" },
    ],
  },
  {
    id: "saas-landing-08",
    category: "saas",
    name: "Cloud Service",
    description:
      "Enterprise cloud service page with uptime stats, security features, global infrastructure map, and tiered pricing.",
    tags: ["cloud", "enterprise", "infrastructure", "security"],
    sections: [
      { sectionId: "header-008" },
      { sectionId: "hero-015", props: { heading: "Cloud Infrastructure That Scales" } },
      { sectionId: "stats-007" },
      { sectionId: "features-015" },
      { sectionId: "logos-005" },
      { sectionId: "testimonials-007" },
      { sectionId: "pricing-008" },
      { sectionId: "cta-008" },
      { sectionId: "footer-008" },
    ],
  },
  {
    id: "saas-landing-09",
    category: "saas",
    name: "Productivity Tool",
    description:
      "Productivity SaaS page focused on time savings and workflow efficiency with before/after comparisons and user stories.",
    tags: ["productivity", "workflow", "efficiency", "tool"],
    sections: [
      { sectionId: "header-009" },
      { sectionId: "hero-017", props: { heading: "Get More Done in Less Time" } },
      { sectionId: "features-017" },
      { sectionId: "video-003" },
      { sectionId: "stats-008" },
      { sectionId: "testimonials-008" },
      { sectionId: "pricing-009" },
      { sectionId: "cta-009" },
      { sectionId: "footer-009" },
    ],
  },
  {
    id: "saas-landing-10",
    category: "saas",
    name: "CRM Platform",
    description:
      "CRM product page with pipeline visuals, feature walkthrough, customer success stories, and scalable pricing plans.",
    tags: ["crm", "sales", "pipeline", "enterprise"],
    sections: [
      { sectionId: "header-010" },
      { sectionId: "hero-019", props: { heading: "Close Deals Faster" } },
      { sectionId: "logos-006" },
      { sectionId: "features-019" },
      { sectionId: "stats-009" },
      { sectionId: "testimonials-009" },
      { sectionId: "pricing-010" },
      { sectionId: "faq-005" },
      { sectionId: "cta-010" },
      { sectionId: "footer-010" },
    ],
  },
  {
    id: "saas-landing-11",
    category: "saas",
    name: "Project Management",
    description:
      "Project management tool page with team collaboration features, Gantt chart previews, and integration ecosystem.",
    tags: ["project-management", "collaboration", "teams", "agile"],
    sections: [
      { sectionId: "header-011" },
      { sectionId: "hero-021", props: { heading: "Manage Projects, Not Chaos" } },
      { sectionId: "features-021" },
      { sectionId: "video-004" },
      { sectionId: "logos-007" },
      { sectionId: "testimonials-010" },
      { sectionId: "pricing-011" },
      { sectionId: "cta-011" },
      { sectionId: "footer-011" },
    ],
  },
  {
    id: "saas-landing-12",
    category: "saas",
    name: "DevOps Tool",
    description:
      "DevOps platform page with CI/CD pipeline visuals, monitoring dashboards, uptime guarantees, and team-based pricing.",
    tags: ["devops", "ci-cd", "monitoring", "infrastructure"],
    sections: [
      { sectionId: "header-012" },
      { sectionId: "hero-023", props: { heading: "Ship With Confidence" } },
      { sectionId: "stats-010" },
      { sectionId: "features-023" },
      { sectionId: "logos-008" },
      { sectionId: "testimonials-011" },
      { sectionId: "pricing-012" },
      { sectionId: "faq-007" },
      { sectionId: "cta-012" },
      { sectionId: "footer-012" },
    ],
  },

  // ==========================================================================
  // 2. Agency / Marketing (10 templates)
  // ==========================================================================
  {
    id: "agency-01",
    category: "agency",
    name: "Digital Agency",
    description:
      "Full-service digital agency page with portfolio gallery, service features, client logos, and team showcase.",
    tags: ["agency", "digital", "services", "portfolio"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-002", props: { heading: "We Build Digital Experiences" } },
      { sectionId: "logos-001" },
      { sectionId: "features-002" },
      { sectionId: "gallery-002" },
      { sectionId: "testimonials-002" },
      { sectionId: "team-001" },
      { sectionId: "cta-002" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "agency-02",
    category: "agency",
    name: "Creative Studio",
    description:
      "Bold creative studio page with immersive hero, project gallery, creative process overview, and contact form.",
    tags: ["creative", "studio", "design", "bold"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-004", props: { heading: "Creativity Without Limits" } },
      { sectionId: "gallery-003" },
      { sectionId: "about-001" },
      { sectionId: "features-004" },
      { sectionId: "testimonials-004" },
      { sectionId: "contact-001" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "agency-03",
    category: "agency",
    name: "Marketing Agency",
    description:
      "Performance marketing agency page with case study stats, service breakdown, client results, and lead capture form.",
    tags: ["marketing", "performance", "growth", "results"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-006", props: { heading: "Marketing That Moves the Needle" } },
      { sectionId: "stats-002" },
      { sectionId: "features-006" },
      { sectionId: "logos-003" },
      { sectionId: "testimonials-006" },
      { sectionId: "cta-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "agency-04",
    category: "agency",
    name: "Design Firm",
    description:
      "Elegant design firm page with portfolio showcase, design philosophy, team bios, and client testimonials.",
    tags: ["design", "elegant", "minimal", "portfolio"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-008" },
      { sectionId: "gallery-004" },
      { sectionId: "about-002" },
      { sectionId: "team-002" },
      { sectionId: "testimonials-008" },
      { sectionId: "contact-002" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "agency-05",
    category: "agency",
    name: "SEO Company",
    description:
      "SEO-focused agency page with ranking stats, service tiers, case study results, and a free audit CTA.",
    tags: ["seo", "search", "rankings", "optimization"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-010", props: { heading: "Rank Higher, Grow Faster" } },
      { sectionId: "stats-004" },
      { sectionId: "features-010" },
      { sectionId: "pricing-006" },
      { sectionId: "testimonials-010" },
      { sectionId: "faq-004" },
      { sectionId: "cta-005" },
      { sectionId: "footer-005" },
    ],
  },
  {
    id: "agency-06",
    category: "agency",
    name: "PR Agency",
    description:
      "Public relations agency page with media coverage logos, service highlights, notable clients, and press inquiry form.",
    tags: ["pr", "public-relations", "media", "communications"],
    sections: [
      { sectionId: "header-006" },
      { sectionId: "hero-012" },
      { sectionId: "logos-004" },
      { sectionId: "features-012" },
      { sectionId: "stats-006" },
      { sectionId: "testimonials-012" },
      { sectionId: "contact-003" },
      { sectionId: "footer-006" },
    ],
  },
  {
    id: "agency-07",
    category: "agency",
    name: "Branding Agency",
    description:
      "Branding-focused agency page with brand identity showcases, process timeline, team profiles, and project inquiry CTA.",
    tags: ["branding", "identity", "strategy", "visual"],
    sections: [
      { sectionId: "header-007" },
      { sectionId: "hero-014", props: { heading: "Brands That Stand Out" } },
      { sectionId: "gallery-005" },
      { sectionId: "about-003" },
      { sectionId: "features-014" },
      { sectionId: "team-003" },
      { sectionId: "cta-007" },
      { sectionId: "footer-007" },
    ],
  },
  {
    id: "agency-08",
    category: "agency",
    name: "Social Media Agency",
    description:
      "Social media management agency page with platform stats, content examples, package pricing, and onboarding CTA.",
    tags: ["social-media", "content", "engagement", "platforms"],
    sections: [
      { sectionId: "header-008" },
      { sectionId: "hero-016", props: { heading: "Social Media That Converts" } },
      { sectionId: "stats-008" },
      { sectionId: "features-016" },
      { sectionId: "gallery-006" },
      { sectionId: "pricing-008" },
      { sectionId: "testimonials-014" },
      { sectionId: "cta-008" },
      { sectionId: "footer-008" },
    ],
  },
  {
    id: "agency-09",
    category: "agency",
    name: "Content Agency",
    description:
      "Content creation agency page with blog previews, content types, editorial process, and subscription plans.",
    tags: ["content", "writing", "editorial", "copywriting"],
    sections: [
      { sectionId: "header-009" },
      { sectionId: "hero-018" },
      { sectionId: "features-018" },
      { sectionId: "blog-001" },
      { sectionId: "testimonials-016" },
      { sectionId: "pricing-009" },
      { sectionId: "cta-009" },
      { sectionId: "footer-009" },
    ],
  },
  {
    id: "agency-10",
    category: "agency",
    name: "Growth Agency",
    description:
      "Growth hacking agency page with ROI stats, growth framework overview, case studies, and strategy call booking.",
    tags: ["growth", "hacking", "roi", "strategy"],
    sections: [
      { sectionId: "header-010" },
      { sectionId: "hero-020", props: { heading: "Accelerate Your Growth" } },
      { sectionId: "stats-010" },
      { sectionId: "features-020" },
      { sectionId: "logos-005" },
      { sectionId: "testimonials-018" },
      { sectionId: "faq-006" },
      { sectionId: "cta-010" },
      { sectionId: "footer-010" },
    ],
  },

  // ==========================================================================
  // 3. Business / Corporate (10 templates)
  // ==========================================================================
  {
    id: "business-01",
    category: "business",
    name: "Corporate Main",
    description:
      "Professional corporate homepage with executive hero, company stats, service overview, leadership team, and contact information.",
    tags: ["corporate", "professional", "enterprise", "formal"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-001" },
      { sectionId: "logos-001" },
      { sectionId: "about-001" },
      { sectionId: "features-001" },
      { sectionId: "stats-001" },
      { sectionId: "team-001" },
      { sectionId: "contact-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "business-02",
    category: "business",
    name: "Consulting Firm",
    description:
      "Consulting firm page with expertise areas, case study highlights, partner logos, and consultation booking CTA.",
    tags: ["consulting", "advisory", "expertise", "professional"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-002", props: { heading: "Strategic Consulting for Growth" } },
      { sectionId: "features-002" },
      { sectionId: "stats-002" },
      { sectionId: "testimonials-001" },
      { sectionId: "team-002" },
      { sectionId: "cta-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "business-03",
    category: "business",
    name: "Financial Services",
    description:
      "Financial services page with trust-building stats, service offerings, compliance badges, and advisory appointment CTA.",
    tags: ["finance", "banking", "investment", "trust"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-004", props: { heading: "Your Financial Future, Secured" } },
      { sectionId: "stats-003" },
      { sectionId: "features-004" },
      { sectionId: "testimonials-003" },
      { sectionId: "faq-002" },
      { sectionId: "contact-002" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "business-04",
    category: "business",
    name: "Law Firm",
    description:
      "Professional law firm page with practice areas, attorney profiles, client testimonials, and case evaluation form.",
    tags: ["law", "legal", "attorney", "professional"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-006" },
      { sectionId: "features-006" },
      { sectionId: "team-004" },
      { sectionId: "testimonials-004" },
      { sectionId: "about-004" },
      { sectionId: "contact-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "business-05",
    category: "business",
    name: "Insurance Company",
    description:
      "Insurance provider page with coverage plans, trust stats, customer reviews, FAQ, and quote request form.",
    tags: ["insurance", "coverage", "protection", "trust"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-008", props: { heading: "Protection You Can Count On" } },
      { sectionId: "features-008" },
      { sectionId: "stats-005" },
      { sectionId: "pricing-001" },
      { sectionId: "testimonials-005" },
      { sectionId: "faq-003" },
      { sectionId: "cta-004" },
      { sectionId: "footer-005" },
    ],
  },
  {
    id: "business-06",
    category: "business",
    name: "Accounting Firm",
    description:
      "Accounting firm page with service listings, industry expertise, team credentials, and free consultation CTA.",
    tags: ["accounting", "tax", "bookkeeping", "financial"],
    sections: [
      { sectionId: "header-006" },
      { sectionId: "hero-010" },
      { sectionId: "features-010" },
      { sectionId: "about-005" },
      { sectionId: "team-005" },
      { sectionId: "testimonials-007" },
      { sectionId: "contact-005" },
      { sectionId: "footer-006" },
    ],
  },
  {
    id: "business-07",
    category: "business",
    name: "Manufacturing Company",
    description:
      "Manufacturing company page with product gallery, capabilities overview, quality certifications, and RFQ form.",
    tags: ["manufacturing", "industrial", "production", "quality"],
    sections: [
      { sectionId: "header-007" },
      { sectionId: "hero-012", props: { heading: "Precision Manufacturing at Scale" } },
      { sectionId: "gallery-007" },
      { sectionId: "features-012" },
      { sectionId: "stats-007" },
      { sectionId: "logos-006" },
      { sectionId: "contact-006" },
      { sectionId: "footer-007" },
    ],
  },
  {
    id: "business-08",
    category: "business",
    name: "Logistics Company",
    description:
      "Logistics and supply chain page with global reach stats, service offerings, tracking features, and quote request form.",
    tags: ["logistics", "shipping", "supply-chain", "global"],
    sections: [
      { sectionId: "header-008" },
      { sectionId: "hero-014" },
      { sectionId: "stats-008" },
      { sectionId: "features-014" },
      { sectionId: "logos-007" },
      { sectionId: "testimonials-009" },
      { sectionId: "contact-007" },
      { sectionId: "footer-008" },
    ],
  },
  {
    id: "business-09",
    category: "business",
    name: "HR Services",
    description:
      "HR services company page with solution areas, client success metrics, team bios, and demo request CTA.",
    tags: ["hr", "human-resources", "recruitment", "talent"],
    sections: [
      { sectionId: "header-009" },
      { sectionId: "hero-016", props: { heading: "Better People, Better Business" } },
      { sectionId: "features-016" },
      { sectionId: "stats-009" },
      { sectionId: "testimonials-011" },
      { sectionId: "team-006" },
      { sectionId: "cta-006" },
      { sectionId: "footer-009" },
    ],
  },
  {
    id: "business-10",
    category: "business",
    name: "Technology Corporation",
    description:
      "Enterprise technology page with innovation showcase, R&D stats, partner ecosystem, leadership team, and investor CTA.",
    tags: ["technology", "enterprise", "innovation", "corporation"],
    sections: [
      { sectionId: "header-010" },
      { sectionId: "hero-018", props: { heading: "Innovating the Future" } },
      { sectionId: "logos-008" },
      { sectionId: "features-018" },
      { sectionId: "stats-010" },
      { sectionId: "about-006" },
      { sectionId: "team-007" },
      { sectionId: "cta-010" },
      { sectionId: "footer-010" },
    ],
  },

  // ==========================================================================
  // 4. Portfolio / Creative (10 templates)
  // ==========================================================================
  {
    id: "portfolio-01",
    category: "portfolio",
    name: "Designer Portfolio",
    description:
      "Minimal designer portfolio with large project gallery, about section, skills overview, and contact form.",
    tags: ["designer", "minimal", "clean", "portfolio"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-003", props: { heading: "Design With Purpose" } },
      { sectionId: "gallery-001" },
      { sectionId: "about-001" },
      { sectionId: "features-003" },
      { sectionId: "testimonials-001" },
      { sectionId: "contact-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "portfolio-02",
    category: "portfolio",
    name: "Photographer Portfolio",
    description:
      "Visual-first photography portfolio with full-width gallery, about the artist section, and booking form.",
    tags: ["photographer", "visual", "gallery", "artistic"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-005" },
      { sectionId: "gallery-003" },
      { sectionId: "divider-001" },
      { sectionId: "about-002" },
      { sectionId: "testimonials-003" },
      { sectionId: "contact-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "portfolio-03",
    category: "portfolio",
    name: "Artist Showcase",
    description:
      "Artistic portfolio page with immersive gallery, biography, exhibition history, and commission inquiry form.",
    tags: ["artist", "gallery", "creative", "showcase"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-007" },
      { sectionId: "gallery-005" },
      { sectionId: "about-003" },
      { sectionId: "stats-003" },
      { sectionId: "contact-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "portfolio-04",
    category: "portfolio",
    name: "Freelancer Portfolio",
    description:
      "Freelancer portfolio with service offerings, project showcase, client testimonials, and availability CTA.",
    tags: ["freelancer", "services", "hire", "independent"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-009", props: { heading: "Freelance Expert for Hire" } },
      { sectionId: "features-009" },
      { sectionId: "gallery-004" },
      { sectionId: "testimonials-005" },
      { sectionId: "pricing-005" },
      { sectionId: "cta-005" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "portfolio-05",
    category: "portfolio",
    name: "Architect Portfolio",
    description:
      "Architecture portfolio featuring project photography, design philosophy, awards, and project inquiry form.",
    tags: ["architect", "architecture", "buildings", "design"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-011" },
      { sectionId: "gallery-006" },
      { sectionId: "about-004" },
      { sectionId: "stats-004" },
      { sectionId: "testimonials-007" },
      { sectionId: "contact-005" },
      { sectionId: "footer-005" },
    ],
  },
  {
    id: "portfolio-06",
    category: "portfolio",
    name: "Videographer Portfolio",
    description:
      "Video-focused portfolio with embedded showreels, project highlights, client list, and booking form.",
    tags: ["videographer", "video", "film", "production"],
    sections: [
      { sectionId: "header-006" },
      { sectionId: "hero-013" },
      { sectionId: "video-001" },
      { sectionId: "gallery-007" },
      { sectionId: "logos-002" },
      { sectionId: "testimonials-009" },
      { sectionId: "contact-006" },
      { sectionId: "footer-006" },
    ],
  },
  {
    id: "portfolio-07",
    category: "portfolio",
    name: "Illustrator Portfolio",
    description:
      "Illustrator portfolio with colorful gallery, style samples, about section, and commission pricing.",
    tags: ["illustrator", "illustration", "art", "colorful"],
    sections: [
      { sectionId: "header-007" },
      { sectionId: "hero-015" },
      { sectionId: "gallery-008" },
      { sectionId: "about-005" },
      { sectionId: "pricing-007" },
      { sectionId: "contact-007" },
      { sectionId: "footer-007" },
    ],
  },
  {
    id: "portfolio-08",
    category: "portfolio",
    name: "UX Designer Portfolio",
    description:
      "UX/UI designer portfolio with case studies, process overview, tools expertise, and project collaboration CTA.",
    tags: ["ux", "ui", "design", "user-experience"],
    sections: [
      { sectionId: "header-008" },
      { sectionId: "hero-017", props: { heading: "Designing User-Centered Experiences" } },
      { sectionId: "gallery-009" },
      { sectionId: "features-017" },
      { sectionId: "about-007" },
      { sectionId: "testimonials-011" },
      { sectionId: "cta-008" },
      { sectionId: "footer-008" },
    ],
  },
  {
    id: "portfolio-09",
    category: "portfolio",
    name: "Writer Portfolio",
    description:
      "Writer portfolio with published works, writing samples, editorial experience, and collaboration inquiry form.",
    tags: ["writer", "author", "copywriter", "editorial"],
    sections: [
      { sectionId: "header-009" },
      { sectionId: "hero-019" },
      { sectionId: "blog-002" },
      { sectionId: "about-008" },
      { sectionId: "testimonials-013" },
      { sectionId: "contact-008" },
      { sectionId: "footer-009" },
    ],
  },
  {
    id: "portfolio-10",
    category: "portfolio",
    name: "Creative Studio Portfolio",
    description:
      "Multi-discipline creative studio portfolio with diverse project gallery, team section, services, and new project CTA.",
    tags: ["studio", "creative", "multidiscipline", "team"],
    sections: [
      { sectionId: "header-010" },
      { sectionId: "hero-021", props: { heading: "Where Ideas Come to Life" } },
      { sectionId: "gallery-010" },
      { sectionId: "features-021" },
      { sectionId: "team-008" },
      { sectionId: "testimonials-015" },
      { sectionId: "cta-011" },
      { sectionId: "footer-010" },
    ],
  },

  // ==========================================================================
  // 5. Landing Pages (12 templates)
  // ==========================================================================
  {
    id: "landing-01",
    category: "landing",
    name: "Product Launch",
    description:
      "High-conversion product launch page with countdown-style hero, key benefits, social proof, and pre-order CTA.",
    tags: ["launch", "product", "conversion", "countdown"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "banner-001" },
      { sectionId: "hero-001", props: { heading: "Introducing Something Revolutionary" } },
      { sectionId: "features-001" },
      { sectionId: "video-001" },
      { sectionId: "testimonials-001" },
      { sectionId: "cta-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "landing-02",
    category: "landing",
    name: "App Download",
    description:
      "Mobile app download page with device mockups, feature highlights, user reviews, and app store CTAs.",
    tags: ["app", "download", "mobile", "install"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-003", props: { heading: "Download the App Today" } },
      { sectionId: "features-003" },
      { sectionId: "gallery-001" },
      { sectionId: "stats-001" },
      { sectionId: "testimonials-003" },
      { sectionId: "cta-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "landing-03",
    category: "landing",
    name: "Webinar Registration",
    description:
      "Webinar signup page with speaker details, agenda highlights, countdown timer, and registration form.",
    tags: ["webinar", "registration", "event", "online"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-005", props: { heading: "Join Our Free Webinar" } },
      { sectionId: "features-005" },
      { sectionId: "team-001" },
      { sectionId: "testimonials-005" },
      { sectionId: "faq-001" },
      { sectionId: "cta-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "landing-04",
    category: "landing",
    name: "Lead Capture",
    description:
      "Focused lead generation page with compelling value proposition, benefit list, trust badges, and email capture form.",
    tags: ["lead", "capture", "generation", "email"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-007", props: { heading: "Get Your Free Strategy Guide" } },
      { sectionId: "features-007" },
      { sectionId: "stats-003" },
      { sectionId: "testimonials-007" },
      { sectionId: "newsletter-002" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "landing-05",
    category: "landing",
    name: "Coming Soon",
    description:
      "Pre-launch coming soon page with teaser hero, feature previews, newsletter signup, and social links.",
    tags: ["coming-soon", "pre-launch", "teaser", "signup"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-009", props: { heading: "Something Big Is Coming" } },
      { sectionId: "features-009" },
      { sectionId: "newsletter-003" },
      { sectionId: "footer-005" },
    ],
  },
  {
    id: "landing-06",
    category: "landing",
    name: "Free Trial",
    description:
      "Free trial signup page with product benefits, feature comparison, user testimonials, and no-credit-card-required CTA.",
    tags: ["trial", "free", "signup", "conversion"],
    sections: [
      { sectionId: "header-006" },
      { sectionId: "hero-011", props: { heading: "Start Your Free Trial" } },
      { sectionId: "features-011" },
      { sectionId: "stats-005" },
      { sectionId: "pricing-006" },
      { sectionId: "testimonials-009" },
      { sectionId: "faq-004" },
      { sectionId: "cta-006" },
      { sectionId: "footer-006" },
    ],
  },
  {
    id: "landing-07",
    category: "landing",
    name: "Newsletter Signup",
    description:
      "Newsletter subscription page with content previews, subscriber count, issue highlights, and prominent signup form.",
    tags: ["newsletter", "email", "subscribe", "content"],
    sections: [
      { sectionId: "header-007" },
      { sectionId: "hero-013", props: { heading: "Join 50,000+ Subscribers" } },
      { sectionId: "blog-003" },
      { sectionId: "stats-007" },
      { sectionId: "testimonials-011" },
      { sectionId: "newsletter-004" },
      { sectionId: "footer-007" },
    ],
  },
  {
    id: "landing-08",
    category: "landing",
    name: "Ebook Download",
    description:
      "Ebook download page with book preview, chapter highlights, author bio, reader reviews, and download CTA.",
    tags: ["ebook", "download", "book", "resource"],
    sections: [
      { sectionId: "header-008" },
      { sectionId: "hero-015", props: { heading: "Download Your Free Ebook" } },
      { sectionId: "features-015" },
      { sectionId: "about-009" },
      { sectionId: "testimonials-013" },
      { sectionId: "cta-008" },
      { sectionId: "footer-008" },
    ],
  },
  {
    id: "landing-09",
    category: "landing",
    name: "Course Enrollment",
    description:
      "Online course enrollment page with curriculum overview, instructor bio, student testimonials, and enrollment CTA.",
    tags: ["course", "enrollment", "education", "learning"],
    sections: [
      { sectionId: "header-009" },
      { sectionId: "hero-017", props: { heading: "Master New Skills Today" } },
      { sectionId: "video-003" },
      { sectionId: "features-017" },
      { sectionId: "team-009" },
      { sectionId: "testimonials-015" },
      { sectionId: "pricing-009" },
      { sectionId: "faq-005" },
      { sectionId: "cta-009" },
      { sectionId: "footer-009" },
    ],
  },
  {
    id: "landing-10",
    category: "landing",
    name: "Waitlist",
    description:
      "Exclusive waitlist page with product teaser, early access benefits, social proof counter, and email signup.",
    tags: ["waitlist", "exclusive", "early-access", "launch"],
    sections: [
      { sectionId: "header-010" },
      { sectionId: "hero-019", props: { heading: "Join the Waitlist" } },
      { sectionId: "features-019" },
      { sectionId: "stats-009" },
      { sectionId: "newsletter-005" },
      { sectionId: "footer-010" },
    ],
  },
  {
    id: "landing-11",
    category: "landing",
    name: "Contest & Giveaway",
    description:
      "Contest landing page with prize showcase, entry rules, countdown, past winner gallery, and entry form.",
    tags: ["contest", "giveaway", "competition", "prizes"],
    sections: [
      { sectionId: "header-011" },
      { sectionId: "hero-021", props: { heading: "Win Big This Month" } },
      { sectionId: "features-021" },
      { sectionId: "gallery-011" },
      { sectionId: "faq-007" },
      { sectionId: "cta-011" },
      { sectionId: "footer-011" },
    ],
  },
  {
    id: "landing-12",
    category: "landing",
    name: "Survey & Feedback",
    description:
      "Survey invitation page with purpose explanation, incentive details, estimated time, and survey link CTA.",
    tags: ["survey", "feedback", "research", "questionnaire"],
    sections: [
      { sectionId: "header-012" },
      { sectionId: "hero-023", props: { heading: "We Value Your Feedback" } },
      { sectionId: "features-023" },
      { sectionId: "stats-011" },
      { sectionId: "cta-012" },
      { sectionId: "footer-012" },
    ],
  },

  // ==========================================================================
  // 6. E-commerce (8 templates)
  // ==========================================================================
  {
    id: "ecommerce-shop-01",
    category: "ecommerce",
    name: "Fashion Store",
    description:
      "Stylish fashion e-commerce page with seasonal hero, product grid, lookbook gallery, and newsletter signup.",
    tags: ["fashion", "clothing", "style", "shopping"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "banner-002" },
      { sectionId: "hero-002", props: { heading: "New Season Collection" } },
      { sectionId: "ecommerce-001" },
      { sectionId: "gallery-002" },
      { sectionId: "ecommerce-003" },
      { sectionId: "testimonials-002" },
      { sectionId: "newsletter-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "ecommerce-shop-02",
    category: "ecommerce",
    name: "Electronics Store",
    description:
      "Tech-focused electronics store page with featured products, category grid, comparison features, and deals banner.",
    tags: ["electronics", "tech", "gadgets", "store"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "banner-003" },
      { sectionId: "hero-004", props: { heading: "Latest Tech, Best Prices" } },
      { sectionId: "ecommerce-002" },
      { sectionId: "features-004" },
      { sectionId: "ecommerce-005" },
      { sectionId: "testimonials-004" },
      { sectionId: "newsletter-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "ecommerce-shop-03",
    category: "ecommerce",
    name: "Home Decor Store",
    description:
      "Elegant home decor store with curated collections, room inspiration gallery, designer picks, and style guide.",
    tags: ["home", "decor", "interior", "furniture"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-006", props: { heading: "Transform Your Space" } },
      { sectionId: "ecommerce-004" },
      { sectionId: "gallery-003" },
      { sectionId: "ecommerce-006" },
      { sectionId: "testimonials-006" },
      { sectionId: "newsletter-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "ecommerce-shop-04",
    category: "ecommerce",
    name: "Beauty & Cosmetics",
    description:
      "Beauty brand store with hero video, bestseller products, ingredient highlights, reviews, and loyalty signup.",
    tags: ["beauty", "cosmetics", "skincare", "makeup"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-008" },
      { sectionId: "video-002" },
      { sectionId: "ecommerce-007" },
      { sectionId: "features-008" },
      { sectionId: "testimonials-008" },
      { sectionId: "newsletter-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "ecommerce-shop-05",
    category: "ecommerce",
    name: "Food & Drink Shop",
    description:
      "Artisanal food and drink store with seasonal specials, product categories, origin stories, and subscription box CTA.",
    tags: ["food", "drink", "artisanal", "gourmet"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-010", props: { heading: "Taste the Difference" } },
      { sectionId: "ecommerce-008" },
      { sectionId: "about-010" },
      { sectionId: "ecommerce-010" },
      { sectionId: "testimonials-010" },
      { sectionId: "cta-005" },
      { sectionId: "footer-005" },
    ],
  },
  {
    id: "ecommerce-shop-06",
    category: "ecommerce",
    name: "Sports & Outdoor Store",
    description:
      "Active sports store with action hero, gear categories, athlete endorsements, and seasonal sale banner.",
    tags: ["sports", "outdoor", "fitness", "gear"],
    sections: [
      { sectionId: "header-006" },
      { sectionId: "banner-004" },
      { sectionId: "hero-012", props: { heading: "Gear Up for Adventure" } },
      { sectionId: "ecommerce-009" },
      { sectionId: "gallery-006" },
      { sectionId: "ecommerce-011" },
      { sectionId: "testimonials-012" },
      { sectionId: "footer-006" },
    ],
  },
  {
    id: "ecommerce-shop-07",
    category: "ecommerce",
    name: "Digital Products Store",
    description:
      "Digital products marketplace with instant download hero, product previews, customer reviews, and bundle pricing.",
    tags: ["digital", "downloads", "templates", "resources"],
    sections: [
      { sectionId: "header-007" },
      { sectionId: "hero-014", props: { heading: "Premium Digital Resources" } },
      { sectionId: "ecommerce-012" },
      { sectionId: "features-014" },
      { sectionId: "ecommerce-013" },
      { sectionId: "testimonials-014" },
      { sectionId: "pricing-007" },
      { sectionId: "faq-006" },
      { sectionId: "footer-007" },
    ],
  },
  {
    id: "ecommerce-shop-08",
    category: "ecommerce",
    name: "Marketplace",
    description:
      "Multi-vendor marketplace with category browsing, featured sellers, trending products, and seller signup CTA.",
    tags: ["marketplace", "multi-vendor", "platform", "sellers"],
    sections: [
      { sectionId: "header-008" },
      { sectionId: "hero-016", props: { heading: "Shop From the Best" } },
      { sectionId: "ecommerce-014" },
      { sectionId: "logos-004" },
      { sectionId: "ecommerce-015" },
      { sectionId: "stats-008" },
      { sectionId: "testimonials-016" },
      { sectionId: "cta-008" },
      { sectionId: "footer-008" },
    ],
  },

  // ==========================================================================
  // 7. Blog / Magazine (8 templates)
  // ==========================================================================
  {
    id: "blog-site-01",
    category: "blog",
    name: "Tech Blog",
    description:
      "Clean tech blog with featured article hero, latest posts grid, category navigation, and newsletter subscription.",
    tags: ["tech", "blog", "articles", "news"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-001", props: { heading: "Insights on Technology" } },
      { sectionId: "blog-001" },
      { sectionId: "divider-002" },
      { sectionId: "blog-003" },
      { sectionId: "newsletter-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "blog-site-02",
    category: "blog",
    name: "Lifestyle Blog",
    description:
      "Warm lifestyle blog with visual hero, post categories, featured articles, and social media follow CTA.",
    tags: ["lifestyle", "blog", "personal", "wellness"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-003" },
      { sectionId: "blog-002" },
      { sectionId: "gallery-002" },
      { sectionId: "blog-005" },
      { sectionId: "newsletter-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "blog-site-03",
    category: "blog",
    name: "News Portal",
    description:
      "News-style portal with breaking news banner, top stories, category sections, and subscription paywall CTA.",
    tags: ["news", "portal", "journalism", "media"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "banner-005" },
      { sectionId: "blog-004" },
      { sectionId: "divider-003" },
      { sectionId: "blog-006" },
      { sectionId: "blog-008" },
      { sectionId: "newsletter-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "blog-site-04",
    category: "blog",
    name: "Travel Blog",
    description:
      "Adventurous travel blog with destination hero, photo galleries, travel guides, and travel tips newsletter.",
    tags: ["travel", "adventure", "destinations", "wanderlust"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-008" },
      { sectionId: "gallery-004" },
      { sectionId: "blog-007" },
      { sectionId: "blog-009" },
      { sectionId: "newsletter-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "blog-site-05",
    category: "blog",
    name: "Food Blog",
    description:
      "Appetizing food blog with recipe hero, latest recipes grid, cooking tips, and weekly recipe newsletter.",
    tags: ["food", "recipes", "cooking", "culinary"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-010", props: { heading: "Delicious Recipes & Stories" } },
      { sectionId: "blog-010" },
      { sectionId: "gallery-005" },
      { sectionId: "blog-011" },
      { sectionId: "newsletter-005" },
      { sectionId: "footer-005" },
    ],
  },
  {
    id: "blog-site-06",
    category: "blog",
    name: "Personal Journal",
    description:
      "Intimate personal journal with minimal hero, chronological posts, about the author, and comment-style contact form.",
    tags: ["personal", "journal", "diary", "minimal"],
    sections: [
      { sectionId: "header-006" },
      { sectionId: "hero-012" },
      { sectionId: "blog-012" },
      { sectionId: "about-006" },
      { sectionId: "newsletter-006" },
      { sectionId: "footer-006" },
    ],
  },
  {
    id: "blog-site-07",
    category: "blog",
    name: "Company Blog",
    description:
      "Professional company blog with thought leadership hero, categorized posts, team authors, and product CTA.",
    tags: ["company", "business", "thought-leadership", "corporate"],
    sections: [
      { sectionId: "header-007" },
      { sectionId: "hero-014", props: { heading: "From Our Team" } },
      { sectionId: "blog-013" },
      { sectionId: "divider-004" },
      { sectionId: "blog-014" },
      { sectionId: "team-007" },
      { sectionId: "cta-007" },
      { sectionId: "footer-007" },
    ],
  },
  {
    id: "blog-site-08",
    category: "blog",
    name: "Online Magazine",
    description:
      "Digital magazine with cover-story hero, editorial sections, contributor profiles, and premium subscription CTA.",
    tags: ["magazine", "editorial", "publication", "premium"],
    sections: [
      { sectionId: "header-008" },
      { sectionId: "hero-016" },
      { sectionId: "blog-015" },
      { sectionId: "gallery-008" },
      { sectionId: "team-008" },
      { sectionId: "newsletter-007" },
      { sectionId: "cta-008" },
      { sectionId: "footer-008" },
    ],
  },

  // ==========================================================================
  // 8. Personal / Resume (8 templates)
  // ==========================================================================
  {
    id: "personal-01",
    category: "personal",
    name: "Developer Resume",
    description:
      "Developer portfolio-resume with code-inspired hero, tech skills, project showcase, open source stats, and contact form.",
    tags: ["developer", "resume", "programming", "tech"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-002", props: { heading: "Full-Stack Developer" } },
      { sectionId: "features-002" },
      { sectionId: "stats-002" },
      { sectionId: "gallery-001" },
      { sectionId: "testimonials-002" },
      { sectionId: "contact-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "personal-02",
    category: "personal",
    name: "Designer CV",
    description:
      "Creative designer CV page with visual hero, design skills showcase, portfolio highlights, and hire-me CTA.",
    tags: ["designer", "cv", "creative", "visual"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-004" },
      { sectionId: "gallery-003" },
      { sectionId: "features-004" },
      { sectionId: "about-002" },
      { sectionId: "testimonials-004" },
      { sectionId: "cta-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "personal-03",
    category: "personal",
    name: "Executive Profile",
    description:
      "Executive personal brand page with professional hero, career highlights, speaking engagements, and advisory inquiry form.",
    tags: ["executive", "leadership", "professional", "corporate"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-006", props: { heading: "Leadership That Delivers" } },
      { sectionId: "about-003" },
      { sectionId: "stats-003" },
      { sectionId: "features-006" },
      { sectionId: "logos-003" },
      { sectionId: "contact-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "personal-04",
    category: "personal",
    name: "Freelancer Profile",
    description:
      "Freelancer personal page with services, hourly rates, client testimonials, availability calendar link, and contact form.",
    tags: ["freelancer", "services", "rates", "available"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-009" },
      { sectionId: "features-009" },
      { sectionId: "pricing-004" },
      { sectionId: "testimonials-006" },
      { sectionId: "about-004" },
      { sectionId: "contact-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "personal-05",
    category: "personal",
    name: "Speaker Profile",
    description:
      "Professional speaker page with keynote video, talk topics, event logos, testimonials, and booking inquiry form.",
    tags: ["speaker", "keynote", "events", "public-speaking"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-011", props: { heading: "Inspiring Audiences Worldwide" } },
      { sectionId: "video-004" },
      { sectionId: "features-011" },
      { sectionId: "logos-005" },
      { sectionId: "testimonials-009" },
      { sectionId: "contact-005" },
      { sectionId: "footer-005" },
    ],
  },
  {
    id: "personal-06",
    category: "personal",
    name: "Consultant Profile",
    description:
      "Consultant personal brand page with expertise areas, methodology overview, case results, and strategy session booking.",
    tags: ["consultant", "strategy", "expertise", "advisory"],
    sections: [
      { sectionId: "header-006" },
      { sectionId: "hero-013" },
      { sectionId: "features-013" },
      { sectionId: "about-005" },
      { sectionId: "stats-005" },
      { sectionId: "testimonials-011" },
      { sectionId: "cta-006" },
      { sectionId: "footer-006" },
    ],
  },
  {
    id: "personal-07",
    category: "personal",
    name: "Teacher Profile",
    description:
      "Educator personal page with teaching philosophy, course offerings, student reviews, and enrollment CTA.",
    tags: ["teacher", "educator", "courses", "learning"],
    sections: [
      { sectionId: "header-007" },
      { sectionId: "hero-015", props: { heading: "Learn From an Expert" } },
      { sectionId: "about-007" },
      { sectionId: "features-015" },
      { sectionId: "testimonials-013" },
      { sectionId: "pricing-007" },
      { sectionId: "contact-007" },
      { sectionId: "footer-007" },
    ],
  },
  {
    id: "personal-08",
    category: "personal",
    name: "Entrepreneur Profile",
    description:
      "Entrepreneur personal brand page with venture highlights, media features, startup stats, and connect CTA.",
    tags: ["entrepreneur", "startup", "founder", "business"],
    sections: [
      { sectionId: "header-008" },
      { sectionId: "hero-017", props: { heading: "Building the Future" } },
      { sectionId: "about-008" },
      { sectionId: "stats-007" },
      { sectionId: "logos-006" },
      { sectionId: "blog-001" },
      { sectionId: "contact-008" },
      { sectionId: "footer-008" },
    ],
  },

  // ==========================================================================
  // 9. Restaurant / Food (5 templates)
  // ==========================================================================
  {
    id: "restaurant-01",
    category: "restaurant",
    name: "Fine Dining",
    description:
      "Elegant fine dining restaurant page with atmospheric hero, menu highlights, chef profile, reviews, and reservation CTA.",
    tags: ["fine-dining", "elegant", "upscale", "restaurant"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-002", props: { heading: "An Unforgettable Dining Experience" } },
      { sectionId: "gallery-001" },
      { sectionId: "features-002" },
      { sectionId: "about-001" },
      { sectionId: "testimonials-001" },
      { sectionId: "contact-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "restaurant-02",
    category: "restaurant",
    name: "Cafe & Coffee Shop",
    description:
      "Cozy cafe page with warm hero imagery, menu previews, our story section, location map, and loyalty program signup.",
    tags: ["cafe", "coffee", "cozy", "casual"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-004" },
      { sectionId: "gallery-003" },
      { sectionId: "features-004" },
      { sectionId: "about-002" },
      { sectionId: "testimonials-003" },
      { sectionId: "newsletter-001" },
      { sectionId: "contact-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "restaurant-03",
    category: "restaurant",
    name: "Fast Food & Quick Service",
    description:
      "Bold fast food page with menu hero, combo deals, location finder, app download CTA, and order-online button.",
    tags: ["fast-food", "quick-service", "bold", "ordering"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "banner-006" },
      { sectionId: "hero-006", props: { heading: "Fresh, Fast, Delicious" } },
      { sectionId: "ecommerce-001" },
      { sectionId: "features-006" },
      { sectionId: "gallery-004" },
      { sectionId: "cta-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "restaurant-04",
    category: "restaurant",
    name: "Food Truck",
    description:
      "Fun food truck page with vibrant hero, daily menu, location schedule, Instagram gallery, and catering inquiry form.",
    tags: ["food-truck", "street-food", "mobile", "fun"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-008", props: { heading: "Find Us on the Streets" } },
      { sectionId: "features-008" },
      { sectionId: "gallery-005" },
      { sectionId: "testimonials-005" },
      { sectionId: "contact-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "restaurant-05",
    category: "restaurant",
    name: "Bakery & Pastry Shop",
    description:
      "Sweet bakery page with pastry hero gallery, product categories, our story, custom order form, and location details.",
    tags: ["bakery", "pastry", "sweet", "artisan"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-010" },
      { sectionId: "gallery-006" },
      { sectionId: "ecommerce-003" },
      { sectionId: "about-005" },
      { sectionId: "testimonials-007" },
      { sectionId: "contact-005" },
      { sectionId: "footer-005" },
    ],
  },

  // ==========================================================================
  // 10. Real Estate (5 templates)
  // ==========================================================================
  {
    id: "realestate-01",
    category: "realestate",
    name: "Agent Portfolio",
    description:
      "Real estate agent page with professional hero, featured listings, client testimonials, market stats, and contact form.",
    tags: ["agent", "realtor", "listings", "professional"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-001", props: { heading: "Your Trusted Real Estate Partner" } },
      { sectionId: "ecommerce-002" },
      { sectionId: "stats-001" },
      { sectionId: "about-001" },
      { sectionId: "testimonials-001" },
      { sectionId: "contact-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "realestate-02",
    category: "realestate",
    name: "Property Listings",
    description:
      "Property listing portal with search hero, featured properties, neighborhood guides, and valuation request CTA.",
    tags: ["listings", "properties", "search", "homes"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-003", props: { heading: "Find Your Dream Home" } },
      { sectionId: "ecommerce-004" },
      { sectionId: "features-003" },
      { sectionId: "ecommerce-006" },
      { sectionId: "stats-002" },
      { sectionId: "testimonials-003" },
      { sectionId: "cta-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "realestate-03",
    category: "realestate",
    name: "Real Estate Agency",
    description:
      "Real estate agency page with brand hero, agent team, service areas, recent sales, and free consultation CTA.",
    tags: ["agency", "real-estate", "team", "services"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-005" },
      { sectionId: "features-005" },
      { sectionId: "team-003" },
      { sectionId: "stats-003" },
      { sectionId: "testimonials-005" },
      { sectionId: "logos-002" },
      { sectionId: "cta-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "realestate-04",
    category: "realestate",
    name: "Luxury Homes",
    description:
      "Luxury real estate page with cinematic hero, exclusive listings, virtual tour videos, and private viewing request form.",
    tags: ["luxury", "premium", "exclusive", "high-end"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-007", props: { heading: "Exceptional Properties, Exceptional Living" } },
      { sectionId: "gallery-007" },
      { sectionId: "video-005" },
      { sectionId: "ecommerce-008" },
      { sectionId: "testimonials-007" },
      { sectionId: "contact-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "realestate-05",
    category: "realestate",
    name: "Commercial Real Estate",
    description:
      "Commercial real estate page with office/retail listings, investment stats, tenant services, and lease inquiry form.",
    tags: ["commercial", "office", "retail", "investment"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-009" },
      { sectionId: "ecommerce-009" },
      { sectionId: "features-009" },
      { sectionId: "stats-005" },
      { sectionId: "testimonials-009" },
      { sectionId: "contact-005" },
      { sectionId: "footer-005" },
    ],
  },

  // ==========================================================================
  // 11. Health / Fitness (5 templates)
  // ==========================================================================
  {
    id: "health-01",
    category: "health",
    name: "Gym & Fitness Center",
    description:
      "Energetic gym page with action hero, class schedule, membership plans, trainer profiles, and free pass CTA.",
    tags: ["gym", "fitness", "workout", "training"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-002", props: { heading: "Transform Your Body" } },
      { sectionId: "features-002" },
      { sectionId: "gallery-002" },
      { sectionId: "pricing-002" },
      { sectionId: "team-002" },
      { sectionId: "testimonials-002" },
      { sectionId: "cta-002" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "health-02",
    category: "health",
    name: "Yoga Studio",
    description:
      "Serene yoga studio page with calming hero, class types, instructor bios, schedule, and trial class signup.",
    tags: ["yoga", "meditation", "wellness", "mindfulness"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-004", props: { heading: "Find Your Inner Balance" } },
      { sectionId: "features-004" },
      { sectionId: "gallery-003" },
      { sectionId: "team-004" },
      { sectionId: "pricing-004" },
      { sectionId: "testimonials-004" },
      { sectionId: "contact-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "health-03",
    category: "health",
    name: "Wellness Center",
    description:
      "Holistic wellness center page with spa-like hero, treatment menu, practitioner profiles, and appointment booking.",
    tags: ["wellness", "spa", "holistic", "health"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-006" },
      { sectionId: "features-006" },
      { sectionId: "gallery-004" },
      { sectionId: "team-005" },
      { sectionId: "testimonials-006" },
      { sectionId: "pricing-006" },
      { sectionId: "contact-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "health-04",
    category: "health",
    name: "Medical Practice",
    description:
      "Trustworthy medical practice page with professional hero, services, doctor profiles, patient reviews, and appointment form.",
    tags: ["medical", "doctor", "clinic", "healthcare"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-008", props: { heading: "Compassionate Care, Expert Results" } },
      { sectionId: "features-008" },
      { sectionId: "team-006" },
      { sectionId: "about-004" },
      { sectionId: "testimonials-008" },
      { sectionId: "faq-004" },
      { sectionId: "contact-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "health-05",
    category: "health",
    name: "Personal Trainer",
    description:
      "Personal trainer page with transformation hero, training programs, client results, pricing packages, and booking form.",
    tags: ["trainer", "personal-training", "fitness", "transformation"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-010", props: { heading: "Your Personal Fitness Journey" } },
      { sectionId: "about-005" },
      { sectionId: "features-010" },
      { sectionId: "gallery-005" },
      { sectionId: "stats-004" },
      { sectionId: "testimonials-010" },
      { sectionId: "pricing-010" },
      { sectionId: "cta-005" },
      { sectionId: "footer-005" },
    ],
  },

  // ==========================================================================
  // 12. Education (5 templates)
  // ==========================================================================
  {
    id: "education-01",
    category: "education",
    name: "Online Course Platform",
    description:
      "Online course platform page with featured courses, instructor spotlight, student stats, pricing, and enrollment CTA.",
    tags: ["courses", "online-learning", "education", "platform"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "hero-001", props: { heading: "Learn From Industry Experts" } },
      { sectionId: "ecommerce-001" },
      { sectionId: "features-001" },
      { sectionId: "team-001" },
      { sectionId: "stats-001" },
      { sectionId: "testimonials-001" },
      { sectionId: "pricing-001" },
      { sectionId: "cta-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "education-02",
    category: "education",
    name: "University Homepage",
    description:
      "University homepage with campus hero, program highlights, faculty showcase, campus gallery, and application CTA.",
    tags: ["university", "college", "campus", "academic"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-003" },
      { sectionId: "features-003" },
      { sectionId: "stats-002" },
      { sectionId: "gallery-002" },
      { sectionId: "team-003" },
      { sectionId: "testimonials-003" },
      { sectionId: "blog-002" },
      { sectionId: "cta-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "education-03",
    category: "education",
    name: "Tutorial Site",
    description:
      "Tutorial and learning resource site with categorized tutorials, latest lessons, instructor bios, and subscription plans.",
    tags: ["tutorials", "learning", "how-to", "resources"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "hero-005", props: { heading: "Learn Something New Today" } },
      { sectionId: "blog-004" },
      { sectionId: "features-005" },
      { sectionId: "video-003" },
      { sectionId: "pricing-003" },
      { sectionId: "testimonials-005" },
      { sectionId: "newsletter-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "education-04",
    category: "education",
    name: "Language School",
    description:
      "Language school page with multilingual hero, course levels, native teachers, student reviews, and placement test CTA.",
    tags: ["language", "school", "multilingual", "immersive"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-007", props: { heading: "Speak a New Language With Confidence" } },
      { sectionId: "features-007" },
      { sectionId: "team-004" },
      { sectionId: "pricing-004" },
      { sectionId: "testimonials-007" },
      { sectionId: "faq-003" },
      { sectionId: "cta-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "education-05",
    category: "education",
    name: "Coding Bootcamp",
    description:
      "Coding bootcamp page with career-change hero, curriculum overview, alumni outcomes, mentor team, and apply-now CTA.",
    tags: ["coding", "bootcamp", "programming", "career"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-009", props: { heading: "Launch Your Tech Career" } },
      { sectionId: "features-009" },
      { sectionId: "stats-005" },
      { sectionId: "video-005" },
      { sectionId: "team-005" },
      { sectionId: "testimonials-009" },
      { sectionId: "pricing-005" },
      { sectionId: "cta-005" },
      { sectionId: "footer-005" },
    ],
  },

  // ==========================================================================
  // 13. Event / Wedding (5 templates)
  // ==========================================================================
  {
    id: "event-01",
    category: "event",
    name: "Conference",
    description:
      "Professional conference page with keynote hero, speaker lineup, schedule highlights, sponsor logos, and ticket purchasing.",
    tags: ["conference", "summit", "professional", "speakers"],
    sections: [
      { sectionId: "header-001" },
      { sectionId: "banner-007" },
      { sectionId: "hero-001", props: { heading: "The Premier Industry Conference" } },
      { sectionId: "team-001" },
      { sectionId: "features-001" },
      { sectionId: "stats-001" },
      { sectionId: "logos-001" },
      { sectionId: "pricing-001" },
      { sectionId: "faq-001" },
      { sectionId: "footer-001" },
    ],
  },
  {
    id: "event-02",
    category: "event",
    name: "Wedding",
    description:
      "Romantic wedding page with couple hero, love story timeline, venue gallery, RSVP form, and event details.",
    tags: ["wedding", "romantic", "celebration", "love"],
    sections: [
      { sectionId: "header-002" },
      { sectionId: "hero-004", props: { heading: "We're Getting Married" } },
      { sectionId: "about-002" },
      { sectionId: "gallery-003" },
      { sectionId: "features-004" },
      { sectionId: "contact-002" },
      { sectionId: "footer-002" },
    ],
  },
  {
    id: "event-03",
    category: "event",
    name: "Music Festival",
    description:
      "Vibrant music festival page with lineup hero, artist gallery, ticket tiers, venue info, and early-bird CTA.",
    tags: ["music", "festival", "concert", "entertainment"],
    sections: [
      { sectionId: "header-003" },
      { sectionId: "banner-008" },
      { sectionId: "hero-006", props: { heading: "Three Days of Incredible Music" } },
      { sectionId: "gallery-004" },
      { sectionId: "team-003" },
      { sectionId: "pricing-003" },
      { sectionId: "faq-002" },
      { sectionId: "contact-003" },
      { sectionId: "footer-003" },
    ],
  },
  {
    id: "event-04",
    category: "event",
    name: "Workshop & Masterclass",
    description:
      "Workshop landing page with instructor hero, curriculum outline, past attendee testimonials, and limited-seat booking CTA.",
    tags: ["workshop", "masterclass", "hands-on", "learning"],
    sections: [
      { sectionId: "header-004" },
      { sectionId: "hero-008", props: { heading: "Hands-On Workshop Experience" } },
      { sectionId: "video-006" },
      { sectionId: "features-008" },
      { sectionId: "team-004" },
      { sectionId: "testimonials-008" },
      { sectionId: "pricing-008" },
      { sectionId: "cta-004" },
      { sectionId: "footer-004" },
    ],
  },
  {
    id: "event-05",
    category: "event",
    name: "Charity Gala",
    description:
      "Elegant charity gala page with cause hero, impact stats, honoree profiles, sponsor recognition, and donation CTA.",
    tags: ["charity", "gala", "fundraiser", "nonprofit"],
    sections: [
      { sectionId: "header-005" },
      { sectionId: "hero-010", props: { heading: "An Evening of Impact" } },
      { sectionId: "about-010" },
      { sectionId: "stats-004" },
      { sectionId: "team-005" },
      { sectionId: "gallery-005" },
      { sectionId: "logos-005" },
      { sectionId: "cta-005" },
      { sectionId: "footer-005" },
    ],
  },
];

registerTemplates(templates);

export { templates };
